In [3]:
import numpy as np

# --- Task 1: Create Arrays ---
# 1D array from 1 to 10
arr_1d = np.arange(1, 11)
print("1D Array:", arr_1d)

# 2D array (3x3) with random integers (например, от 0 до 10)
arr_2d = np.random.randint(10, size=(3, 3))
print("\n2D Array (Random):\n", arr_2d)

# --- Task 2: Array Operations ---
# Sum, mean, max
print(f"\nSum: {arr_2d.sum()}, Mean: {arr_2d.mean():.2f}, Max: {arr_2d.max()}")

# Multiply all elements by 2
arr_multiplied = arr_2d * 2
print("\nMultiplied by 2:\n", arr_multiplied)

# Replace all values greater than 5 with 0
arr_replaced = np.where(arr_2d > 5, 0, arr_2d)
print("\nReplaced (>5 becomes 0):\n", arr_replaced)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]

2D Array (Random):
 [[7 7 6]
 [9 9 3]
 [3 2 3]]

Sum: 49, Mean: 5.44, Max: 9

Multiplied by 2:
 [[14 14 12]
 [18 18  6]
 [ 6  4  6]]

Replaced (>5 becomes 0):
 [[0 0 0]
 [0 0 3]
 [3 2 3]]
